### ISSUE TITLE
Questions on pyyaks

### ISSUE THREAD

**Issue by cdeil** [taldcroft/pyyaks#3]
@taldcroft - I'm currently looking for a data analysis pipeline toolkit for Gammapy and found this.

I haven't tried it yet, but:
- would you recommend this or are you using something else by now?
- can you add an open-source license?

**Comment by taldcroft** [comment]
@cdeil - sorry for the delay, this slipped off my radar before answering.

Yes, I'm still using pyyaks, though I'm not really doing much heavy pipeline processing now.  In new code I mostly am taking advantage of the context variables for managing projects with lots of file names.

I would recommend it if you don't find anything that seems better to you.  It has worked for doing some reasonably complex pipeline processing, e.g. the Chandra C-COSMOS and CygOB2 XVP data.

I'll add a LICENSE shortly.  However, note that development on this project is now taking place (occasionally) at https://github.com/sot/pyyaks.  This the account for the Chandra Science Operations Team.

**Comment by cdeil** [comment]
@taldcroft - Thanks for adding the license and the info!
